name: test
on: [push]

jobs:
  test:
    name: Node.js ${{ matrix.node_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [10, 12]

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            **/node_modules
          key: cache-${{ matrix.node_version }}-${{ hashFiles('**/package.json') }}
      - run: npm install
      - run: npm test -- --serial
        env:
          FORCE_COLOR: true
